name: krono
description: A secure and private file vault

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.0.1
  shared_preferences: ^2.0.18
  flutter_riverpod: ^2.3.0
  cached_network_image: ^3.2.3
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  firebase_crashlytics: ^3.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
